#!/usr/bin/env python3

import re
import sys
from pathlib import Path


def escape_cpp_string(text: str) -> str:
    return 'R"iris_err(\n' + text + '\n)iris_err"'


def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <error_codes_dir> <output_file>")
        sys.exit(1)

    codes_dir = Path(sys.argv[1])
    out_file  = Path(sys.argv[2])

    pattern = re.compile(r'^E(\d+)\.md$', re.IGNORECASE)
    entries: list[tuple[int, str]] = []

    for md_file in sorted(codes_dir.iterdir()):
        m = pattern.match(md_file.name)
        if not m:
            continue
        code = int(m.group(1))
        text = md_file.read_text(encoding='utf-8')
        entries.append((code, text))

    entries.sort(key=lambda e: e[0])

    lines: list[str] = [
        "// Generated by gen_errors.py - do not edit.",
        "#pragma once",
        "#include <string_view>",
        "#include <array>",
        "",
        "struct ErrorDoc {",
        "  unsigned int code;",
        "  std::string_view text;",
        "};",
        "",
        f"inline constexpr std::array<ErrorDoc, {len(entries)}> k_errorDocs{{{{",
    ]

    for code, text in entries:
        escaped = escape_cpp_string(text)
        lines.append(f"  ErrorDoc{{{code}u, {escaped}}},")

    lines += [
        "}};",
        "",
        "inline constexpr std::string_view lookupErrorDoc(unsigned int code) noexcept {",
        "  for (const auto& doc : k_errorDocs)",
        "    if (doc.code == code) return doc.text;",
        '  return "";',
        "}",
    ]

    out_file.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f"Generated {out_file} with {len(entries)} error code(s).")


if __name__ == '__main__':
    main()