#!/usr/bin/env python3

import re
import sys
from pathlib import Path

PATTERN = re.compile(r'^E(\d+)\.md$', re.IGNORECASE)

def escape_cpp_string(text: str) -> str:
    return 'R"doc(\n' + text + '\n)doc"'

def load_entries(codes_dir: Path) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []

    for md_file in sorted(codes_dir.iterdir()):
        if not md_file.is_file():
            continue
        m = PATTERN.match(md_file.name)
        if not m:
            if md_file.suffix.lower() == '.md':
                print(f"warning: skipping '{md_file.name}' — filename does not match E<code>.md")
            continue
        entries.append((int(m.group(1)), md_file.read_text(encoding='utf-8')))

    entries.sort(key=lambda e: e[0])

    for i in range(1, len(entries)):
        if entries[i][0] == entries[i - 1][0]:
            print(f"error: duplicate error code E{entries[i][0]:04d}", file=sys.stderr)
            sys.exit(1)

    return entries

def generate(entries: list[tuple[int, str]]) -> str:
    lines: list[str] = [
        "// Generated by gen_errors.py — do not edit.",
        "#pragma once",
        "#include <algorithm>",
        "#include <array>",
        "#include <string_view>",
        "",
        "struct ErrorDoc {",
        "  unsigned int code;",
        "  std::string_view text;",
        "};",
        "",
        f"inline constexpr std::array<ErrorDoc, {len(entries)}> k_errorDocs{{{{",
    ]

    for code, text in entries:
        lines.append(f"  ErrorDoc{{{code}u, {escape_cpp_string(text)}}},")

    lines += [
        "}};",
        "",
        "inline constexpr std::string_view lookupErrorDoc(unsigned int code) noexcept {",
        "  auto it = std::lower_bound(",
        "    k_errorDocs.begin(), k_errorDocs.end(), code,",
        "    [](const ErrorDoc &doc, unsigned int c) { return doc.code < c; });",
        "  if (it != k_errorDocs.end() && it->code == code)",
        "    return it->text;",
        '  return "";',
        "}",
        "",
    ]

    return '\n'.join(lines)

def main() -> None:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <error_codes_dir> <output_file>")
        sys.exit(1)

    codes_dir = Path(sys.argv[1])
    out_file  = Path(sys.argv[2])

    if not codes_dir.is_dir():
        print(f"error: '{codes_dir}' is not a directory", file=sys.stderr)
        sys.exit(1)

    entries = load_entries(codes_dir)
    out_file.write_text(generate(entries), encoding='utf-8')
    print(f"Generated {out_file} with {len(entries)} error code(s).")
    
if __name__ == '__main__':
    main()